version: '3.7'

services:
    gateway:
        image: baranbartu/k-api-gateway:latest
        command: sh -c "uvicorn main:app --reload --host 0.0.0.0"
        build:
            context: ./gateway
            dockerfile: Dockerfile
        env_file:
            - ./gateway/.env
        ports:
          - 8001:8000
        depends_on:
          - products
          - orders
        volumes:
          - ./gateway:/app

    products:
        image: baranbartu/k-products:latest
        command: sh -c "uvicorn main:app --reload --host 0.0.0.0"
        build:
            context: ./products
            dockerfile: Dockerfile
        volumes:
          - ./products:/app

    orders:
        image: baranbartu/k-orders:latest
        command: sh -c "uvicorn main:app --reload --host 0.0.0.0"
        build:
            context: ./orders
            dockerfile: Dockerfile
        volumes:
          - ./orders:/app